# Generated by Django 2.2.4 on 2020-12-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='confirmed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
