# Generated by Django 2.2.4 on 2021-01-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_auto_20201223_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmKey',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
